# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import (
        Content,
        ContentExternalUrls,
        CreateAppealResponse,
        CreateAppealResponseData,
        CreateAppealResponseDataActionStatus,
        ErrorResponse,
        ErrorResponseError,
        GetApiV1RecordsRequestStatus,
        GetApiV1UsersRequestStatus,
        IngestRecordRequest,
        IngestRecordResponse,
        IngestUserResponse,
        ListRecordsResponse,
        ListUsersResponse,
        Metadata,
        ModerateResponse,
        ModerateResponseStatus,
        Record,
        RecordInput,
        RecordModerationStatus,
        RecordResponse,
        SuccessResponse,
        User,
        UserActionStatus,
        UserInput,
        UserResponse,
    )
    from .errors import (
        BadRequestError,
        ConflictError,
        ForbiddenError,
        InternalServerError,
        NotFoundError,
        ServiceUnavailableError,
        UnauthorizedError,
    )
    from ._default_clients import DefaultAioHttpClient, DefaultAsyncHttpxClient
    from .client import AsyncInsionClient, InsionClient
    from .environment import InsionClientEnvironment
_dynamic_imports: typing.Dict[str, str] = {
    "AsyncInsionClient": ".client",
    "BadRequestError": ".errors",
    "ConflictError": ".errors",
    "Content": ".types",
    "ContentExternalUrls": ".types",
    "CreateAppealResponse": ".types",
    "CreateAppealResponseData": ".types",
    "CreateAppealResponseDataActionStatus": ".types",
    "DefaultAioHttpClient": "._default_clients",
    "DefaultAsyncHttpxClient": "._default_clients",
    "ErrorResponse": ".types",
    "ErrorResponseError": ".types",
    "ForbiddenError": ".errors",
    "GetApiV1RecordsRequestStatus": ".types",
    "GetApiV1UsersRequestStatus": ".types",
    "IngestRecordRequest": ".types",
    "IngestRecordResponse": ".types",
    "IngestUserResponse": ".types",
    "InsionClient": ".client",
    "InsionClientEnvironment": ".environment",
    "InternalServerError": ".errors",
    "ListRecordsResponse": ".types",
    "ListUsersResponse": ".types",
    "Metadata": ".types",
    "ModerateResponse": ".types",
    "ModerateResponseStatus": ".types",
    "NotFoundError": ".errors",
    "Record": ".types",
    "RecordInput": ".types",
    "RecordModerationStatus": ".types",
    "RecordResponse": ".types",
    "ServiceUnavailableError": ".errors",
    "SuccessResponse": ".types",
    "UnauthorizedError": ".errors",
    "User": ".types",
    "UserActionStatus": ".types",
    "UserInput": ".types",
    "UserResponse": ".types",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "AsyncInsionClient",
    "BadRequestError",
    "ConflictError",
    "Content",
    "ContentExternalUrls",
    "CreateAppealResponse",
    "CreateAppealResponseData",
    "CreateAppealResponseDataActionStatus",
    "DefaultAioHttpClient",
    "DefaultAsyncHttpxClient",
    "ErrorResponse",
    "ErrorResponseError",
    "ForbiddenError",
    "GetApiV1RecordsRequestStatus",
    "GetApiV1UsersRequestStatus",
    "IngestRecordRequest",
    "IngestRecordResponse",
    "IngestUserResponse",
    "InsionClient",
    "InsionClientEnvironment",
    "InternalServerError",
    "ListRecordsResponse",
    "ListUsersResponse",
    "Metadata",
    "ModerateResponse",
    "ModerateResponseStatus",
    "NotFoundError",
    "Record",
    "RecordInput",
    "RecordModerationStatus",
    "RecordResponse",
    "ServiceUnavailableError",
    "SuccessResponse",
    "UnauthorizedError",
    "User",
    "UserActionStatus",
    "UserInput",
    "UserResponse",
]
