# This file was auto-generated by Fern from our API Definition.

import typing

import httpx
from .core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from .core.logging import LogConfig, Logger
from .core.request_options import RequestOptions
from .environment import InsionClientEnvironment
from .raw_client import AsyncRawInsionClient, RawInsionClient
from .types.content import Content
from .types.create_appeal_response import CreateAppealResponse
from .types.get_api_v1records_request_status import GetApiV1RecordsRequestStatus
from .types.get_api_v1users_request_status import GetApiV1UsersRequestStatus
from .types.ingest_record_response import IngestRecordResponse
from .types.ingest_user_response import IngestUserResponse
from .types.list_records_response import ListRecordsResponse
from .types.list_users_response import ListUsersResponse
from .types.metadata import Metadata
from .types.moderate_response import ModerateResponse
from .types.record_response import RecordResponse
from .types.success_response import SuccessResponse
from .types.user_input import UserInput
from .types.user_response import UserResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class InsionClient:
    """
    Use this class to access the different functions within the SDK. You can instantiate any number of clients with different configuration that will propagate to these functions.

    Parameters
    ----------
    base_url : typing.Optional[str]
        The base url to use for requests from the client.

    environment : InsionClientEnvironment
        The environment to use for requests from the client. from .environment import InsionClientEnvironment



        Defaults to InsionClientEnvironment.DEFAULT



    token : typing.Union[str, typing.Callable[[], str]]
    headers : typing.Optional[typing.Dict[str, str]]
        Additional headers to send with every request.

    timeout : typing.Optional[float]
        The timeout to be used, in seconds, for requests. By default the timeout is 60 seconds, unless a custom httpx client is used, in which case this default is not enforced.

    max_retries : typing.Optional[int]
        The default maximum number of retries for failed requests. Defaults to 2. Per-request `max_retries` in `request_options` takes precedence over this value.

    stream_reconnection_enabled : typing.Optional[bool]
        Whether to automatically reconnect on stream disconnection for resumable streaming endpoints. Defaults to True. Per-request `stream_reconnection_enabled` in `request_options` takes precedence over this value.

    max_stream_reconnection_attempts : typing.Optional[int]
        The maximum number of reconnection attempts for resumable streaming endpoints. Defaults to no limit. Per-request `max_stream_reconnection_attempts` in `request_options` takes precedence over this value.

    follow_redirects : typing.Optional[bool]
        Whether the default httpx client follows redirects or not, this is irrelevant if a custom httpx client is passed in.

    httpx_client : typing.Optional[httpx.Client]
        The httpx client to use for making requests, a preconfigured client is used by default, however this is useful should you want to pass in any custom httpx configuration.

    logging : typing.Optional[typing.Union[LogConfig, Logger]]
        Configure logging for the SDK. Accepts a LogConfig dict with 'level' (debug/info/warn/error), 'logger' (custom logger implementation), and 'silent' (boolean, defaults to True) fields. You can also pass a pre-configured Logger instance.

    Examples
    --------
    from insion import InsionClient

    client = InsionClient(
        token="YOUR_TOKEN",
    )
    """

    def __init__(
        self,
        *,
        base_url: typing.Optional[str] = None,
        environment: InsionClientEnvironment = InsionClientEnvironment.DEFAULT,
        token: typing.Union[str, typing.Callable[[], str]],
        headers: typing.Optional[typing.Dict[str, str]] = None,
        timeout: typing.Optional[float] = None,
        max_retries: typing.Optional[int] = None,
        stream_reconnection_enabled: typing.Optional[bool] = None,
        max_stream_reconnection_attempts: typing.Optional[int] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.Client] = None,
        logging: typing.Optional[typing.Union[LogConfig, Logger]] = None,
    ):
        _defaulted_timeout = timeout if timeout is not None else 60 if httpx_client is None else None
        _defaulted_max_retries = max_retries if max_retries is not None else 2
        self._client_wrapper = SyncClientWrapper(
            base_url=_get_base_url(base_url=base_url, environment=environment),
            token=token,
            headers=headers,
            httpx_client=httpx_client
            if httpx_client is not None
            else httpx.Client(timeout=_defaulted_timeout, follow_redirects=follow_redirects)
            if follow_redirects is not None
            else httpx.Client(timeout=_defaulted_timeout),
            timeout=_defaulted_timeout,
            max_retries=_defaulted_max_retries,
            stream_reconnection_enabled=stream_reconnection_enabled,
            max_stream_reconnection_attempts=max_stream_reconnection_attempts,
            logging=logging,
        )
        self._raw_client = RawInsionClient(client_wrapper=self._client_wrapper)

    @property
    def with_raw_response(self) -> RawInsionClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawInsionClient
        """
        return self._raw_client

    def moderate_a_record(
        self,
        *,
        client_id: str,
        name: str,
        entity: str,
        content: Content,
        passthrough: typing.Optional[bool] = OMIT,
        client_url: typing.Optional[str] = OMIT,
        metadata: typing.Optional[Metadata] = OMIT,
        user: typing.Optional[UserInput] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ModerateResponse:
        """
        Create or update a record and return its moderation result immediately.

        Parameters
        ----------
        client_id : str
            Your unique identifier for the record.

        name : str
            Name or title of the record.

        entity : str
            Type of record, such as post, comment, or message.

        content : Content

        passthrough : typing.Optional[bool]
            Moderate without persisting the record's name or content, or the user's email, name, or username.

        client_url : typing.Optional[str]
            URL for the original content.

        metadata : typing.Optional[Metadata]

        user : typing.Optional[UserInput]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ModerateResponse
            Content was moderated successfully.

        Examples
        --------
        from insion import InsionClient

        client = InsionClient(
            token="YOUR_TOKEN",
        )
        client.moderate_a_record(
            client_id="clientId",
            name="name",
            entity="entity",
            content="content",
        )
        """
        _response = self._raw_client.moderate_a_record(
            client_id=client_id,
            name=name,
            entity=entity,
            content=content,
            passthrough=passthrough,
            client_url=client_url,
            metadata=metadata,
            user=user,
            request_options=request_options,
        )
        return _response.data

    def ingest_a_record(
        self,
        *,
        client_id: str,
        name: str,
        entity: str,
        content: Content,
        client_url: typing.Optional[str] = OMIT,
        metadata: typing.Optional[Metadata] = OMIT,
        user: typing.Optional[UserInput] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> IngestRecordResponse:
        """
        Create or update a content record for asynchronous moderation. Results are delivered through webhook events when moderation is performed.

        Parameters
        ----------
        client_id : str
            Your unique identifier for the record.

        name : str
            Name or title of the record.

        entity : str
            Type of record, such as post, comment, or message.

        content : Content

        client_url : typing.Optional[str]
            URL for the original content.

        metadata : typing.Optional[Metadata]

        user : typing.Optional[UserInput]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        IngestRecordResponse
            Record was created or updated successfully.

        Examples
        --------
        from insion import InsionClient

        client = InsionClient(
            token="YOUR_TOKEN",
        )
        client.ingest_a_record(
            client_id="clientId",
            name="name",
            entity="entity",
            content="content",
        )
        """
        _response = self._raw_client.ingest_a_record(
            client_id=client_id,
            name=name,
            entity=entity,
            content=content,
            client_url=client_url,
            metadata=metadata,
            user=user,
            request_options=request_options,
        )
        return _response.data

    def delete_a_record(
        self, *, client_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> SuccessResponse:
        """
        Remove a record from the moderation system by its client ID.

        Parameters
        ----------
        client_id : str
            Your unique identifier for the record.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SuccessResponse
            Record was deleted successfully.

        Examples
        --------
        from insion import InsionClient

        client = InsionClient(
            token="YOUR_TOKEN",
        )
        client.delete_a_record(
            client_id="clientId",
        )
        """
        _response = self._raw_client.delete_a_record(client_id=client_id, request_options=request_options)
        return _response.data

    def ingest_a_user(
        self,
        *,
        client_id: str,
        client_url: typing.Optional[str] = OMIT,
        stripe_account_id: typing.Optional[str] = OMIT,
        email: typing.Optional[str] = OMIT,
        name: typing.Optional[str] = OMIT,
        username: typing.Optional[str] = OMIT,
        protected: typing.Optional[bool] = OMIT,
        metadata: typing.Optional[Metadata] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> IngestUserResponse:
        """
        Create or update a user without ingesting a record.

        Parameters
        ----------
        client_id : str
            Your unique identifier for the user.

        client_url : typing.Optional[str]
            URL for the user's profile.

        stripe_account_id : typing.Optional[str]
            The user's Stripe account ID.

        email : typing.Optional[str]
            The user's email address.

        name : typing.Optional[str]
            The user's name.

        username : typing.Optional[str]
            The user's username.

        protected : typing.Optional[bool]
            Whether the user is protected from automated moderation actions.

        metadata : typing.Optional[Metadata]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        IngestUserResponse
            User was created or updated successfully.

        Examples
        --------
        from insion import InsionClient

        client = InsionClient(
            token="YOUR_TOKEN",
        )
        client.ingest_a_user(
            client_id="clientId",
        )
        """
        _response = self._raw_client.ingest_a_user(
            client_id=client_id,
            client_url=client_url,
            stripe_account_id=stripe_account_id,
            email=email,
            name=name,
            username=username,
            protected=protected,
            metadata=metadata,
            request_options=request_options,
        )
        return _response.data

    def list_records(
        self,
        *,
        limit: typing.Optional[int] = None,
        starting_after: typing.Optional[str] = None,
        ending_before: typing.Optional[str] = None,
        client_id: typing.Optional[str] = None,
        user: typing.Optional[str] = None,
        entity: typing.Optional[str] = None,
        status: typing.Optional[GetApiV1RecordsRequestStatus] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListRecordsResponse:
        """
        List the records belonging to the authenticated organization.

        Parameters
        ----------
        limit : typing.Optional[int]
            Maximum number of items to return.

        starting_after : typing.Optional[str]
            Return items after this Insion ID. Cannot be used with ending_before.

        ending_before : typing.Optional[str]
            Return items before this Insion ID. Cannot be used with starting_after.

        client_id : typing.Optional[str]
            Filter by your record identifier.

        user : typing.Optional[str]
            Filter by Insion user ID.

        entity : typing.Optional[str]
            Filter by record entity.

        status : typing.Optional[GetApiV1RecordsRequestStatus]
            Filter by moderation status.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListRecordsResponse
            A page of records.

        Examples
        --------
        from insion import InsionClient

        client = InsionClient(
            token="YOUR_TOKEN",
        )
        client.list_records()
        """
        _response = self._raw_client.list_records(
            limit=limit,
            starting_after=starting_after,
            ending_before=ending_before,
            client_id=client_id,
            user=user,
            entity=entity,
            status=status,
            request_options=request_options,
        )
        return _response.data

    def retrieve_a_record(
        self, record_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> RecordResponse:
        """
        Retrieve one record by its Insion record ID.

        Parameters
        ----------
        record_id : str
            Insion record ID.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RecordResponse
            The requested record.

        Examples
        --------
        from insion import InsionClient

        client = InsionClient(
            token="YOUR_TOKEN",
        )
        client.retrieve_a_record(
            record_id="recordId",
        )
        """
        _response = self._raw_client.retrieve_a_record(record_id, request_options=request_options)
        return _response.data

    def list_users(
        self,
        *,
        limit: typing.Optional[int] = None,
        starting_after: typing.Optional[str] = None,
        ending_before: typing.Optional[str] = None,
        client_id: typing.Optional[str] = None,
        email: typing.Optional[str] = None,
        status: typing.Optional[GetApiV1UsersRequestStatus] = None,
        user: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListUsersResponse:
        """
        List the users belonging to the authenticated organization.

        Parameters
        ----------
        limit : typing.Optional[int]
            Maximum number of items to return.

        starting_after : typing.Optional[str]
            Return items after this Insion ID. Cannot be used with ending_before.

        ending_before : typing.Optional[str]
            Return items before this Insion ID. Cannot be used with starting_after.

        client_id : typing.Optional[str]
            Filter by your user identifier.

        email : typing.Optional[str]
            Filter by user email.

        status : typing.Optional[GetApiV1UsersRequestStatus]
            Filter by user action status.

        user : typing.Optional[str]
            Filter by Insion user ID.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListUsersResponse
            A page of users.

        Examples
        --------
        from insion import InsionClient

        client = InsionClient(
            token="YOUR_TOKEN",
        )
        client.list_users()
        """
        _response = self._raw_client.list_users(
            limit=limit,
            starting_after=starting_after,
            ending_before=ending_before,
            client_id=client_id,
            email=email,
            status=status,
            user=user,
            request_options=request_options,
        )
        return _response.data

    def retrieve_a_user(self, user_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> UserResponse:
        """
        Retrieve one user by its Insion user ID.

        Parameters
        ----------
        user_id : str
            Insion user ID.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UserResponse
            The requested user.

        Examples
        --------
        from insion import InsionClient

        client = InsionClient(
            token="YOUR_TOKEN",
        )
        client.retrieve_a_user(
            user_id="userId",
        )
        """
        _response = self._raw_client.retrieve_a_user(user_id, request_options=request_options)
        return _response.data

    def create_an_appeal(
        self, user_id: str, *, text: str, request_options: typing.Optional[RequestOptions] = None
    ) -> CreateAppealResponse:
        """
        Create an appeal for a suspended user. Appeals must be enabled for the organization.

        Parameters
        ----------
        user_id : str
            Insion user ID.

        text : str
            The appeal message.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateAppealResponse
            Appeal created successfully.

        Examples
        --------
        from insion import InsionClient

        client = InsionClient(
            token="YOUR_TOKEN",
        )
        client.create_an_appeal(
            user_id="userId",
            text="text",
        )
        """
        _response = self._raw_client.create_an_appeal(user_id, text=text, request_options=request_options)
        return _response.data


def _make_default_async_client(
    timeout: typing.Optional[float],
    follow_redirects: typing.Optional[bool],
) -> httpx.AsyncClient:
    try:
        import httpx_aiohttp  # type: ignore[import-not-found]
    except ImportError:
        pass
    else:
        if follow_redirects is not None:
            return httpx_aiohttp.HttpxAiohttpClient(timeout=timeout, follow_redirects=follow_redirects)
        return httpx_aiohttp.HttpxAiohttpClient(timeout=timeout)

    if follow_redirects is not None:
        return httpx.AsyncClient(timeout=timeout, follow_redirects=follow_redirects)
    return httpx.AsyncClient(timeout=timeout)


class AsyncInsionClient:
    """
    Use this class to access the different functions within the SDK. You can instantiate any number of clients with different configuration that will propagate to these functions.

    Parameters
    ----------
    base_url : typing.Optional[str]
        The base url to use for requests from the client.

    environment : InsionClientEnvironment
        The environment to use for requests from the client. from .environment import InsionClientEnvironment



        Defaults to InsionClientEnvironment.DEFAULT



    token : typing.Union[str, typing.Callable[[], str]]
    headers : typing.Optional[typing.Dict[str, str]]
        Additional headers to send with every request.

    async_token : typing.Optional[typing.Callable[[], typing.Awaitable[str]]]
        An async callable that returns a bearer token. Use this when token acquisition involves async I/O (e.g., refreshing tokens via an async HTTP client). When provided, this is used instead of the synchronous token for async requests.

    timeout : typing.Optional[float]
        The timeout to be used, in seconds, for requests. By default the timeout is 60 seconds, unless a custom httpx client is used, in which case this default is not enforced.

    max_retries : typing.Optional[int]
        The default maximum number of retries for failed requests. Defaults to 2. Per-request `max_retries` in `request_options` takes precedence over this value.

    stream_reconnection_enabled : typing.Optional[bool]
        Whether to automatically reconnect on stream disconnection for resumable streaming endpoints. Defaults to True. Per-request `stream_reconnection_enabled` in `request_options` takes precedence over this value.

    max_stream_reconnection_attempts : typing.Optional[int]
        The maximum number of reconnection attempts for resumable streaming endpoints. Defaults to no limit. Per-request `max_stream_reconnection_attempts` in `request_options` takes precedence over this value.

    follow_redirects : typing.Optional[bool]
        Whether the default httpx client follows redirects or not, this is irrelevant if a custom httpx client is passed in.

    httpx_client : typing.Optional[httpx.AsyncClient]
        The httpx client to use for making requests, a preconfigured client is used by default, however this is useful should you want to pass in any custom httpx configuration.

    logging : typing.Optional[typing.Union[LogConfig, Logger]]
        Configure logging for the SDK. Accepts a LogConfig dict with 'level' (debug/info/warn/error), 'logger' (custom logger implementation), and 'silent' (boolean, defaults to True) fields. You can also pass a pre-configured Logger instance.

    Examples
    --------
    from insion import AsyncInsionClient

    client = AsyncInsionClient(
        token="YOUR_TOKEN",
    )
    """

    def __init__(
        self,
        *,
        base_url: typing.Optional[str] = None,
        environment: InsionClientEnvironment = InsionClientEnvironment.DEFAULT,
        token: typing.Union[str, typing.Callable[[], str]],
        headers: typing.Optional[typing.Dict[str, str]] = None,
        async_token: typing.Optional[typing.Callable[[], typing.Awaitable[str]]] = None,
        timeout: typing.Optional[float] = None,
        max_retries: typing.Optional[int] = None,
        stream_reconnection_enabled: typing.Optional[bool] = None,
        max_stream_reconnection_attempts: typing.Optional[int] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.AsyncClient] = None,
        logging: typing.Optional[typing.Union[LogConfig, Logger]] = None,
    ):
        _defaulted_timeout = timeout if timeout is not None else 60 if httpx_client is None else None
        _defaulted_max_retries = max_retries if max_retries is not None else 2
        self._client_wrapper = AsyncClientWrapper(
            base_url=_get_base_url(base_url=base_url, environment=environment),
            token=token,
            headers=headers,
            async_token=async_token,
            httpx_client=httpx_client
            if httpx_client is not None
            else _make_default_async_client(timeout=_defaulted_timeout, follow_redirects=follow_redirects),
            timeout=_defaulted_timeout,
            max_retries=_defaulted_max_retries,
            stream_reconnection_enabled=stream_reconnection_enabled,
            max_stream_reconnection_attempts=max_stream_reconnection_attempts,
            logging=logging,
        )
        self._raw_client = AsyncRawInsionClient(client_wrapper=self._client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawInsionClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawInsionClient
        """
        return self._raw_client

    async def moderate_a_record(
        self,
        *,
        client_id: str,
        name: str,
        entity: str,
        content: Content,
        passthrough: typing.Optional[bool] = OMIT,
        client_url: typing.Optional[str] = OMIT,
        metadata: typing.Optional[Metadata] = OMIT,
        user: typing.Optional[UserInput] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ModerateResponse:
        """
        Create or update a record and return its moderation result immediately.

        Parameters
        ----------
        client_id : str
            Your unique identifier for the record.

        name : str
            Name or title of the record.

        entity : str
            Type of record, such as post, comment, or message.

        content : Content

        passthrough : typing.Optional[bool]
            Moderate without persisting the record's name or content, or the user's email, name, or username.

        client_url : typing.Optional[str]
            URL for the original content.

        metadata : typing.Optional[Metadata]

        user : typing.Optional[UserInput]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ModerateResponse
            Content was moderated successfully.

        Examples
        --------
        import asyncio

        from insion import AsyncInsionClient

        client = AsyncInsionClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.moderate_a_record(
                client_id="clientId",
                name="name",
                entity="entity",
                content="content",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.moderate_a_record(
            client_id=client_id,
            name=name,
            entity=entity,
            content=content,
            passthrough=passthrough,
            client_url=client_url,
            metadata=metadata,
            user=user,
            request_options=request_options,
        )
        return _response.data

    async def ingest_a_record(
        self,
        *,
        client_id: str,
        name: str,
        entity: str,
        content: Content,
        client_url: typing.Optional[str] = OMIT,
        metadata: typing.Optional[Metadata] = OMIT,
        user: typing.Optional[UserInput] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> IngestRecordResponse:
        """
        Create or update a content record for asynchronous moderation. Results are delivered through webhook events when moderation is performed.

        Parameters
        ----------
        client_id : str
            Your unique identifier for the record.

        name : str
            Name or title of the record.

        entity : str
            Type of record, such as post, comment, or message.

        content : Content

        client_url : typing.Optional[str]
            URL for the original content.

        metadata : typing.Optional[Metadata]

        user : typing.Optional[UserInput]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        IngestRecordResponse
            Record was created or updated successfully.

        Examples
        --------
        import asyncio

        from insion import AsyncInsionClient

        client = AsyncInsionClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.ingest_a_record(
                client_id="clientId",
                name="name",
                entity="entity",
                content="content",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.ingest_a_record(
            client_id=client_id,
            name=name,
            entity=entity,
            content=content,
            client_url=client_url,
            metadata=metadata,
            user=user,
            request_options=request_options,
        )
        return _response.data

    async def delete_a_record(
        self, *, client_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> SuccessResponse:
        """
        Remove a record from the moderation system by its client ID.

        Parameters
        ----------
        client_id : str
            Your unique identifier for the record.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SuccessResponse
            Record was deleted successfully.

        Examples
        --------
        import asyncio

        from insion import AsyncInsionClient

        client = AsyncInsionClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.delete_a_record(
                client_id="clientId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_a_record(client_id=client_id, request_options=request_options)
        return _response.data

    async def ingest_a_user(
        self,
        *,
        client_id: str,
        client_url: typing.Optional[str] = OMIT,
        stripe_account_id: typing.Optional[str] = OMIT,
        email: typing.Optional[str] = OMIT,
        name: typing.Optional[str] = OMIT,
        username: typing.Optional[str] = OMIT,
        protected: typing.Optional[bool] = OMIT,
        metadata: typing.Optional[Metadata] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> IngestUserResponse:
        """
        Create or update a user without ingesting a record.

        Parameters
        ----------
        client_id : str
            Your unique identifier for the user.

        client_url : typing.Optional[str]
            URL for the user's profile.

        stripe_account_id : typing.Optional[str]
            The user's Stripe account ID.

        email : typing.Optional[str]
            The user's email address.

        name : typing.Optional[str]
            The user's name.

        username : typing.Optional[str]
            The user's username.

        protected : typing.Optional[bool]
            Whether the user is protected from automated moderation actions.

        metadata : typing.Optional[Metadata]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        IngestUserResponse
            User was created or updated successfully.

        Examples
        --------
        import asyncio

        from insion import AsyncInsionClient

        client = AsyncInsionClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.ingest_a_user(
                client_id="clientId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.ingest_a_user(
            client_id=client_id,
            client_url=client_url,
            stripe_account_id=stripe_account_id,
            email=email,
            name=name,
            username=username,
            protected=protected,
            metadata=metadata,
            request_options=request_options,
        )
        return _response.data

    async def list_records(
        self,
        *,
        limit: typing.Optional[int] = None,
        starting_after: typing.Optional[str] = None,
        ending_before: typing.Optional[str] = None,
        client_id: typing.Optional[str] = None,
        user: typing.Optional[str] = None,
        entity: typing.Optional[str] = None,
        status: typing.Optional[GetApiV1RecordsRequestStatus] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListRecordsResponse:
        """
        List the records belonging to the authenticated organization.

        Parameters
        ----------
        limit : typing.Optional[int]
            Maximum number of items to return.

        starting_after : typing.Optional[str]
            Return items after this Insion ID. Cannot be used with ending_before.

        ending_before : typing.Optional[str]
            Return items before this Insion ID. Cannot be used with starting_after.

        client_id : typing.Optional[str]
            Filter by your record identifier.

        user : typing.Optional[str]
            Filter by Insion user ID.

        entity : typing.Optional[str]
            Filter by record entity.

        status : typing.Optional[GetApiV1RecordsRequestStatus]
            Filter by moderation status.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListRecordsResponse
            A page of records.

        Examples
        --------
        import asyncio

        from insion import AsyncInsionClient

        client = AsyncInsionClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.list_records()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_records(
            limit=limit,
            starting_after=starting_after,
            ending_before=ending_before,
            client_id=client_id,
            user=user,
            entity=entity,
            status=status,
            request_options=request_options,
        )
        return _response.data

    async def retrieve_a_record(
        self, record_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> RecordResponse:
        """
        Retrieve one record by its Insion record ID.

        Parameters
        ----------
        record_id : str
            Insion record ID.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RecordResponse
            The requested record.

        Examples
        --------
        import asyncio

        from insion import AsyncInsionClient

        client = AsyncInsionClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.retrieve_a_record(
                record_id="recordId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.retrieve_a_record(record_id, request_options=request_options)
        return _response.data

    async def list_users(
        self,
        *,
        limit: typing.Optional[int] = None,
        starting_after: typing.Optional[str] = None,
        ending_before: typing.Optional[str] = None,
        client_id: typing.Optional[str] = None,
        email: typing.Optional[str] = None,
        status: typing.Optional[GetApiV1UsersRequestStatus] = None,
        user: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListUsersResponse:
        """
        List the users belonging to the authenticated organization.

        Parameters
        ----------
        limit : typing.Optional[int]
            Maximum number of items to return.

        starting_after : typing.Optional[str]
            Return items after this Insion ID. Cannot be used with ending_before.

        ending_before : typing.Optional[str]
            Return items before this Insion ID. Cannot be used with starting_after.

        client_id : typing.Optional[str]
            Filter by your user identifier.

        email : typing.Optional[str]
            Filter by user email.

        status : typing.Optional[GetApiV1UsersRequestStatus]
            Filter by user action status.

        user : typing.Optional[str]
            Filter by Insion user ID.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListUsersResponse
            A page of users.

        Examples
        --------
        import asyncio

        from insion import AsyncInsionClient

        client = AsyncInsionClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.list_users()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_users(
            limit=limit,
            starting_after=starting_after,
            ending_before=ending_before,
            client_id=client_id,
            email=email,
            status=status,
            user=user,
            request_options=request_options,
        )
        return _response.data

    async def retrieve_a_user(
        self, user_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> UserResponse:
        """
        Retrieve one user by its Insion user ID.

        Parameters
        ----------
        user_id : str
            Insion user ID.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UserResponse
            The requested user.

        Examples
        --------
        import asyncio

        from insion import AsyncInsionClient

        client = AsyncInsionClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.retrieve_a_user(
                user_id="userId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.retrieve_a_user(user_id, request_options=request_options)
        return _response.data

    async def create_an_appeal(
        self, user_id: str, *, text: str, request_options: typing.Optional[RequestOptions] = None
    ) -> CreateAppealResponse:
        """
        Create an appeal for a suspended user. Appeals must be enabled for the organization.

        Parameters
        ----------
        user_id : str
            Insion user ID.

        text : str
            The appeal message.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateAppealResponse
            Appeal created successfully.

        Examples
        --------
        import asyncio

        from insion import AsyncInsionClient

        client = AsyncInsionClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.create_an_appeal(
                user_id="userId",
                text="text",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_an_appeal(user_id, text=text, request_options=request_options)
        return _response.data


def _get_base_url(*, base_url: typing.Optional[str] = None, environment: InsionClientEnvironment) -> str:
    if base_url is not None:
        return base_url
    elif environment is not None:
        return environment.value
    else:
        raise Exception("Please pass in either base_url or environment to construct the client")
