# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .content import Content
    from .content_external_urls import ContentExternalUrls
    from .create_appeal_response import CreateAppealResponse
    from .create_appeal_response_data import CreateAppealResponseData
    from .create_appeal_response_data_action_status import CreateAppealResponseDataActionStatus
    from .error_response import ErrorResponse
    from .error_response_error import ErrorResponseError
    from .get_api_v1records_request_status import GetApiV1RecordsRequestStatus
    from .get_api_v1users_request_status import GetApiV1UsersRequestStatus
    from .ingest_record_request import IngestRecordRequest
    from .ingest_record_response import IngestRecordResponse
    from .ingest_user_response import IngestUserResponse
    from .list_records_response import ListRecordsResponse
    from .list_users_response import ListUsersResponse
    from .metadata import Metadata
    from .moderate_response import ModerateResponse
    from .moderate_response_status import ModerateResponseStatus
    from .record import Record
    from .record_input import RecordInput
    from .record_moderation_status import RecordModerationStatus
    from .record_response import RecordResponse
    from .success_response import SuccessResponse
    from .user import User
    from .user_action_status import UserActionStatus
    from .user_input import UserInput
    from .user_response import UserResponse
_dynamic_imports: typing.Dict[str, str] = {
    "Content": ".content",
    "ContentExternalUrls": ".content_external_urls",
    "CreateAppealResponse": ".create_appeal_response",
    "CreateAppealResponseData": ".create_appeal_response_data",
    "CreateAppealResponseDataActionStatus": ".create_appeal_response_data_action_status",
    "ErrorResponse": ".error_response",
    "ErrorResponseError": ".error_response_error",
    "GetApiV1RecordsRequestStatus": ".get_api_v1records_request_status",
    "GetApiV1UsersRequestStatus": ".get_api_v1users_request_status",
    "IngestRecordRequest": ".ingest_record_request",
    "IngestRecordResponse": ".ingest_record_response",
    "IngestUserResponse": ".ingest_user_response",
    "ListRecordsResponse": ".list_records_response",
    "ListUsersResponse": ".list_users_response",
    "Metadata": ".metadata",
    "ModerateResponse": ".moderate_response",
    "ModerateResponseStatus": ".moderate_response_status",
    "Record": ".record",
    "RecordInput": ".record_input",
    "RecordModerationStatus": ".record_moderation_status",
    "RecordResponse": ".record_response",
    "SuccessResponse": ".success_response",
    "User": ".user",
    "UserActionStatus": ".user_action_status",
    "UserInput": ".user_input",
    "UserResponse": ".user_response",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "Content",
    "ContentExternalUrls",
    "CreateAppealResponse",
    "CreateAppealResponseData",
    "CreateAppealResponseDataActionStatus",
    "ErrorResponse",
    "ErrorResponseError",
    "GetApiV1RecordsRequestStatus",
    "GetApiV1UsersRequestStatus",
    "IngestRecordRequest",
    "IngestRecordResponse",
    "IngestUserResponse",
    "ListRecordsResponse",
    "ListUsersResponse",
    "Metadata",
    "ModerateResponse",
    "ModerateResponseStatus",
    "Record",
    "RecordInput",
    "RecordModerationStatus",
    "RecordResponse",
    "SuccessResponse",
    "User",
    "UserActionStatus",
    "UserInput",
    "UserResponse",
]
