# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class ContentExternalUrls(UniversalBaseModel):
    text: str = pydantic.Field()
    """
    Text content to moderate.
    """

    image_urls: typing_extensions.Annotated[
        typing.Optional[typing.List[str]],
        FieldMetadata(alias="imageUrls"),
        pydantic.Field(alias="imageUrls", description="Image URLs to moderate."),
    ] = None
    """
    Image URLs to moderate.
    """

    external_urls: typing_extensions.Annotated[
        typing.Optional[typing.List[str]],
        FieldMetadata(alias="externalUrls"),
        pydantic.Field(alias="externalUrls", description="External page URLs to moderate."),
    ] = None
    """
    External page URLs to moderate.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
