# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .create_appeal_response_data_action_status import CreateAppealResponseDataActionStatus


class CreateAppealResponseData(UniversalBaseModel):
    id: str
    action_status: typing_extensions.Annotated[
        typing.Optional[CreateAppealResponseDataActionStatus],
        FieldMetadata(alias="actionStatus"),
        pydantic.Field(alias="actionStatus"),
    ] = None
    action_status_created_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="actionStatusCreatedAt"),
        pydantic.Field(alias="actionStatusCreatedAt"),
    ] = None
    created_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="createdAt"), pydantic.Field(alias="createdAt")
    ]
    updated_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="updatedAt"), pydantic.Field(alias="updatedAt")
    ]
    appeal_url: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="appealUrl"), pydantic.Field(alias="appealUrl")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
