# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from .success_response import SuccessResponse


class IngestRecordResponse(SuccessResponse):
    id: str = pydantic.Field()
    """
    Insion record ID.
    """

    moderation: typing.Optional[str] = pydantic.Field(default=None)
    """
    Insion moderation ID when moderation was queued; otherwise null.
    """

    user: typing.Optional[str] = pydantic.Field(default=None)
    """
    Insion user ID when a user was provided.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
