# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .moderate_response_status import ModerateResponseStatus


class ModerateResponse(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    Insion record ID.
    """

    status: ModerateResponseStatus = pydantic.Field()
    """
    Moderation status.
    """

    moderation: str = pydantic.Field()
    """
    Insion moderation ID.
    """

    user: typing.Optional[str] = pydantic.Field(default=None)
    """
    Insion user ID when a user was provided.
    """

    message: str
    flagged: bool = pydantic.Field()
    """
    Deprecated. True when status is Flagged.
    """

    category_ids: typing_extensions.Annotated[
        typing.List[str],
        FieldMetadata(alias="categoryIds"),
        pydantic.Field(alias="categoryIds", description="IDs of rules that matched the record."),
    ]
    """
    IDs of rules that matched the record.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
