# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .metadata import Metadata
from .record_moderation_status import RecordModerationStatus


class Record(UniversalBaseModel):
    id: str
    client_id: typing_extensions.Annotated[str, FieldMetadata(alias="clientId"), pydantic.Field(alias="clientId")]
    client_url: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="clientUrl"), pydantic.Field(alias="clientUrl")
    ] = None
    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Name or title of the record. Null when submitted using passthrough moderation.
    """

    entity: str
    protected: bool
    metadata: typing.Optional[Metadata] = None
    created_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="createdAt"), pydantic.Field(alias="createdAt")
    ]
    updated_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="updatedAt"), pydantic.Field(alias="updatedAt")
    ]
    moderation_status: typing_extensions.Annotated[
        typing.Optional[RecordModerationStatus],
        FieldMetadata(alias="moderationStatus"),
        pydantic.Field(alias="moderationStatus"),
    ] = None
    moderation_status_created_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="moderationStatusCreatedAt"),
        pydantic.Field(alias="moderationStatusCreatedAt"),
    ] = None
    moderation_pending: typing_extensions.Annotated[
        bool, FieldMetadata(alias="moderationPending"), pydantic.Field(alias="moderationPending")
    ]
    moderation_pending_created_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="moderationPendingCreatedAt"),
        pydantic.Field(alias="moderationPendingCreatedAt"),
    ] = None
    user: typing.Optional[str] = pydantic.Field(default=None)
    """
    Associated Insion user ID.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
