# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .content import Content
from .metadata import Metadata
from .user_input import UserInput


class RecordInput(UniversalBaseModel):
    client_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="clientId"),
        pydantic.Field(alias="clientId", description="Your unique identifier for the record."),
    ]
    """
    Your unique identifier for the record.
    """

    client_url: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="clientUrl"),
        pydantic.Field(alias="clientUrl", description="URL for the original content."),
    ] = None
    """
    URL for the original content.
    """

    name: str = pydantic.Field()
    """
    Name or title of the record.
    """

    entity: str = pydantic.Field()
    """
    Type of record, such as post, comment, or message.
    """

    content: Content
    metadata: typing.Optional[Metadata] = None
    user: typing.Optional[UserInput] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
