# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .metadata import Metadata


class UserInput(UniversalBaseModel):
    client_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="clientId"),
        pydantic.Field(alias="clientId", description="Your unique identifier for the user."),
    ]
    """
    Your unique identifier for the user.
    """

    client_url: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="clientUrl"),
        pydantic.Field(alias="clientUrl", description="URL for the user's profile."),
    ] = None
    """
    URL for the user's profile.
    """

    stripe_account_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="stripeAccountId"),
        pydantic.Field(alias="stripeAccountId", description="The user's Stripe account ID."),
    ] = None
    """
    The user's Stripe account ID.
    """

    email: typing.Optional[str] = pydantic.Field(default=None)
    """
    The user's email address.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The user's name.
    """

    username: typing.Optional[str] = pydantic.Field(default=None)
    """
    The user's username.
    """

    protected: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether the user is protected from automated moderation actions.
    """

    metadata: typing.Optional[Metadata] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
